SELECT 		
--CASE STATEMENT PARA LOCAL 
CASE 
	WHEN MU.IN_CAPITAL  = 1 THEN 'Capital'
	WHEN MU.IN_CAPITAL = 0 THEN 'Interior'
ELSE NULL
	END AS LOCALIZACAO_MUN,
			MU.CO_MUNICIPIO,
			MU.NO_MUNICIPIO,
			EC.CO_ENTIDADE, 
			EC.NO_ENTIDADE,
--CASE STATEMENT PARA A DEPENDENCIA
CASE 
	WHEN EC.TP_DEPENDENCIA = 1 THEN '1 - FEDERAL'
	WHEN EC.TP_DEPENDENCIA = 2 THEN '2 - ESTADUAL'
	WHEN EC.TP_DEPENDENCIA = 3 THEN '3 - MUNICIPAL'
	WHEN EC.TP_DEPENDENCIA = 4 THEN '4 - PRIVADA'
ELSE NULL
	END AS DEPENDENCIA,
--CASE STATEMENT PARA A LOCALIZAÇÃO 
CASE 
	WHEN EC.TP_LOCALIZACAO = 1 THEN '1 - URBANA'
	WHEN EC.TP_LOCALIZACAO = 2 THEN '2 - RURAL'
ELSE NULL
	END AS LOCALIZACAO,
--CASE STATEMENT PARA A LOCALIZAÇÃO DIFERENCIADA 
CASE 
	WHEN EC.TP_LOCALIZACAO_DIFERENCIADA  = 0 THEN '0 - A escola não está em área de localização diferenciada'
	WHEN EC.TP_LOCALIZACAO_DIFERENCIADA  = 1 THEN '1 - Área de assentamento'
	WHEN EC.TP_LOCALIZACAO_DIFERENCIADA  = 2 THEN '2 - Terra indígena'
	WHEN EC.TP_LOCALIZACAO_DIFERENCIADA  = 3 THEN '3 - Área onde se localiza comunidade remanescente de quilombos'
ELSE NULL
	END AS LOCALIZACAO_DIFERENCIADA,
--CASE STATEMENT PARA A LOCALIZAÇÃO 
CASE 
	WHEN TU.IN_EDUCACAO_INDIGENA = 1 THEN 'SIM'
	WHEN TU.IN_EDUCACAO_INDIGENA = 0 THEN 'NÃO'
ELSE NULL
	END AS EDUCACAO_INDIGENA,
			TU.ID_TURMA, 
			TU.NO_TURMA, 
--CASE STATEMENT PARA MEDIAÇÃO DIDATCO PEDAGOGICA
CASE 
	WHEN TU.TP_MEDIACAO_DIDATICO_PEDAGO = 1 THEN 'Presencial'
	WHEN TU.TP_MEDIACAO_DIDATICO_PEDAGO = 2 THEN 'Semipresencial'
	WHEN TU.TP_MEDIACAO_DIDATICO_PEDAGO = 3 THEN 'Educação a Distância - EAD'
ELSE NULL
	END AS TP_MEDIACAO_DIDATICO_PEDAGO,
			TU.TX_HR_INICIAL, 
			TU.TX_MI_INICIAL,
			TU.NU_DURACAO_TURMA, 
--CASE STATEMENT PARA O TURNO
CASE 
	WHEN TU.NU_DURACAO_TURMA > 420 THEN 'INTEGRAL'
	WHEN (TU.NU_DURACAO_TURMA <= 420) THEN 'PARCIAL'
ELSE NULL
	END AS TURNO,
--CASE STATEMENT PARA LOCAL DE FUNCIONAMENTO DA TURMA 
CASE 
	WHEN TU.TP_TIPO_LOCAL_TURMA = 0 THEN 'A turma não está em local de funcionamento diferenciado'
	WHEN TU.TP_TIPO_LOCAL_TURMA = 1 THEN 'Sala anexa'
	WHEN TU.TP_TIPO_LOCAL_TURMA = 2 THEN 'Unidade de atendimento socioeducativo'
	WHEN TU.TP_TIPO_LOCAL_TURMA = 3 THEN 'Unidade prisional'
ELSE NULL
	END AS TP_TIPO_LOCAL_TURMA,
--CASE STATEMENT PARA A MODALIDADE
CASE 
	WHEN (TU.IN_ESPECIAL_EXCLUSIVA = 0 AND TU.TP_ETAPA_ENSINO IN (74,64,40,39,30,31,32,68,73)) THEN 'PROFISSIONALIZANTE'
	WHEN TU.IN_ESPECIAL_EXCLUSIVA = 1 THEN 'EDUCAÇÃO ESPECIAL'
	WHEN (TU.IN_ESPECIAL_EXCLUSIVA = 0 AND TU.TP_ETAPA_ENSINO IN (69,70,71,72)) THEN 'EJA'
	--WHEN TU.IN_PROFISSIONALIZANTE = 1 THEN 'PROFISSIONALIZANTE'
ELSE 'REGULAR'
	END AS MODALIDADE,
--CASE STATEMENT PARA NIVEL DE ENSINO 
CASE 
	WHEN (MA.TP_ETAPA_ENSINO IN (1,2)) THEN '1 - EDUCAÇÃO INFANTIL'
	WHEN (MA.TP_ETAPA_ENSINO IN (14,15,16,17,18)) THEN '2 - FUNDAMENTAL - ANOS INICIAS'
	WHEN (MA.TP_ETAPA_ENSINO IN (19,20,21,41)) THEN '3 - FUNDAMENTAL - ANOS FINAIS'
	WHEN (MA.TP_ETAPA_ENSINO IN (25,26,27,28,30,31,32)) THEN '4 - ENSINO MÉDIO'
	WHEN (MA.TP_ETAPA_ENSINO IN (69,70)) THEN '5 - EJA FUNDAMENTAL'
	WHEN (MA.TP_ETAPA_ENSINO IN (71)) THEN '6 - EJA MÉDIO'
	WHEN (MA.TP_ETAPA_ENSINO IN (39,40,68,73,74)) THEN '7 - EDUCAÇÃO PROFISSIONAL'
END AS NIVEL_ENSINO,
			TU.TP_ETAPA_ENSINO TU_ETAPA_ENSINO,
			(SELECT ET.NO_ETAPA_ENSINO FROM CENSO_ESCOLAR_EMPILHADO.AUX_ETAPA_ENSINO_ISCED ET WHERE TU.TP_ETAPA_ENSINO = ET.TP_ETAPA_ENSINO AND ET.NU_ANO_CENSO = 2022) AS ETAPA_TURMA,
			MA.TP_ETAPA_ENSINO MA_ETAPA_ENSINO,
			(SELECT ET.NO_ETAPA_ENSINO FROM CENSO_ESCOLAR_EMPILHADO.AUX_ETAPA_ENSINO_ISCED ET WHERE MA.TP_ETAPA_ENSINO = ET.TP_ETAPA_ENSINO AND ET.NU_ANO_CENSO = 2022) AS ETAPA_MATRICULA,
--SUM STATEMENT PARA SOMA DAS IDADES
			SUM(CASE WHEN MA.NU_IDADE  = 0 THEN 1 ELSE 0 END) AS IDADE0,
			SUM(CASE WHEN MA.NU_IDADE  = 1 THEN 1 ELSE 0 END) AS IDADE1,
			SUM(CASE WHEN MA.NU_IDADE  = 2 THEN 1 ELSE 0 END) AS IDADE2,
			SUM(CASE WHEN MA.NU_IDADE  = 3 THEN 1 ELSE 0 END) AS IDADE3,
			SUM(CASE WHEN MA.NU_IDADE  = 4 THEN 1 ELSE 0 END) AS IDADE4,
			SUM(CASE WHEN MA.NU_IDADE  = 5 THEN 1 ELSE 0 END) AS IDADE5,
			SUM(CASE WHEN MA.NU_IDADE  = 6 THEN 1 ELSE 0 END) AS IDADE6,
			SUM(CASE WHEN MA.NU_IDADE  = 7 THEN 1 ELSE 0 END) AS IDADE7,
			SUM(CASE WHEN MA.NU_IDADE  = 8 THEN 1 ELSE 0 END) AS IDADE8,
			SUM(CASE WHEN MA.NU_IDADE  = 9 THEN 1 ELSE 0 END) AS IDADE9,
			SUM(CASE WHEN MA.NU_IDADE  = 10 THEN 1 ELSE 0 END) AS IDADE10,
			SUM(CASE WHEN MA.NU_IDADE  = 11 THEN 1 ELSE 0 END) AS IDADE11,
			SUM(CASE WHEN MA.NU_IDADE  = 12 THEN 1 ELSE 0 END) AS IDADE12,
			SUM(CASE WHEN MA.NU_IDADE  = 13 THEN 1 ELSE 0 END) AS IDADE13,
			SUM(CASE WHEN MA.NU_IDADE  = 14 THEN 1 ELSE 0 END) AS IDADE14,
			SUM(CASE WHEN MA.NU_IDADE  = 15 THEN 1 ELSE 0 END) AS IDADE15,
			SUM(CASE WHEN MA.NU_IDADE  = 16 THEN 1 ELSE 0 END) AS IDADE16,
			SUM(CASE WHEN MA.NU_IDADE  = 17 THEN 1 ELSE 0 END) AS IDADE17,
			SUM(CASE WHEN MA.NU_IDADE  = 18 THEN 1 ELSE 0 END) AS IDADE18,
			SUM(CASE WHEN MA.NU_IDADE  = 19 THEN 1 ELSE 0 END) AS IDADE19,
			SUM(CASE WHEN MA.NU_IDADE  = 20 THEN 1 ELSE 0 END) AS IDADE20,
			SUM(CASE WHEN MA.NU_IDADE  = 21 THEN 1 ELSE 0 END) AS IDADE21,
			SUM(CASE WHEN MA.NU_IDADE  = 22 THEN 1 ELSE 0 END) AS IDADE22,
			SUM(CASE WHEN MA.NU_IDADE  = 23 THEN 1 ELSE 0 END) AS IDADE23,
			SUM(CASE WHEN MA.NU_IDADE  = 24 THEN 1 ELSE 0 END) AS IDADE24,
			SUM(CASE WHEN MA.NU_IDADE  = 25 THEN 1 ELSE 0 END) AS IDADE25,
			SUM(CASE WHEN MA.NU_IDADE  = 26 THEN 1 ELSE 0 END) AS IDADE26,
			SUM(CASE WHEN MA.NU_IDADE  = 27 THEN 1 ELSE 0 END) AS IDADE27,
			SUM(CASE WHEN MA.NU_IDADE  = 28 THEN 1 ELSE 0 END) AS IDADE28,
			SUM(CASE WHEN MA.NU_IDADE  = 29 THEN 1 ELSE 0 END) AS IDADE29,
			SUM(CASE WHEN MA.NU_IDADE  > 29 THEN 1 ELSE 0 END) AS IDADE29MAIOR,
			COUNT(MA.ID_MATRICULA)
--SELEÇÃO DAS TABELAS 
FROM
	CENSO_ESCOLAR_EMPILHADO.TS_CENSO_BASICO_ESCOLA EC,
	CENSO_ESCOLAR_EMPILHADO.TS_CENSO_BASICO_TURMA TU,
	CENSO_ESCOLAR_EMPILHADO.TS_CENSO_BASICO_MATRICULA MA,
	CENSO_ESCOLAR_EMPILHADO.AUX_MUNICIPIO MU
--FILTROS
WHERE 
--INNER JOIN
	(EC.CO_ENTIDADE = TU.CO_ENTIDADE) AND
	(EC.CO_ENTIDADE = MA.CO_ENTIDADE) AND
	(MA.CO_ENTIDADE = TU.CO_ENTIDADE) AND
	(MA.ID_TURMA  = TU.ID_TURMA) AND
	(EC.NU_ANO_CENSO  = TU.NU_ANO_CENSO) AND
	(EC.NU_ANO_CENSO  = MA.NU_ANO_CENSO) AND
	(MA.NU_ANO_CENSO  = TU.NU_ANO_CENSO) AND
	(MU.CO_MUNICIPIO  = EC.CO_MUNICIPIO) AND 
	(MU.NU_ANO_CENSO = EC.NU_ANO_CENSO) AND 
	(MU.NU_ANO_CENSO = TU.NU_ANO_CENSO) AND
	(MU.NU_ANO_CENSO = MA.NU_ANO_CENSO) AND
--FILTROS
	--EC.CO_ENTIDADE = 13094262 AND 
	EC.NU_ANO_CENSO = 2022 	AND 
	TU.TP_TIPO_ATENDIMENTO_TURMA IN (1,2) AND
	--MU.CO_MUNICIPIO = 1302603 AND
	--TU.ID_TURMA = 27742481 AND
	--EC.NO_ENTIDADE LIKE '%MEDIACAO TECNOL%' AND
	MU.CO_UF = 13 
GROUP BY 	MU.IN_CAPITAL,
			MU.CO_MUNICIPIO,
			MU.NO_MUNICIPIO,
			TU.ID_TURMA,
			TU.IN_EDUCACAO_INDIGENA,
			EC.CO_ENTIDADE, 
			EC.NO_ENTIDADE, 
			EC.TP_DEPENDENCIA, 
			EC.TP_LOCALIZACAO,
			EC.TP_LOCALIZACAO_DIFERENCIADA,
			TU.ID_TURMA, 
			TU.NO_TURMA, 
			TU.TP_MEDIACAO_DIDATICO_PEDAGO, 
			TU.TX_HR_INICIAL, TU.TX_MI_INICIAL,
			TU.NU_DURACAO_TURMA, 
			TU.TP_TIPO_LOCAL_TURMA, 
			TU.TP_ETAPA_ENSINO, 
			--TU.IN_REGULAR, 
			TU.IN_ESPECIAL_EXCLUSIVA, 
			--TU.IN_EJA,
			--TU.IN_PROFISSIONALIZANTE,
			MA.TP_ETAPA_ENSINO